server:
  port: 8111
spring:
  datasource:
    url: jdbc:oracle:thin:@//narods-scan.azerconnect.az:1521/SRVPDBNGBSS
    username: JHIPSTER
    password: AZRC2018GdBD+
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      schema: JHIPSTER
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle12cDialect
